library(sqldf)
Power <- read.csv.sql("household_power_consumption.txt","select * from file where Date = '1/2/2007' or Date = '2/2/2007' ",sep=";")
Date_Time <- paste(Power$Date, Power$Time)
Date_Time <- as.POSIXct(strptime(Date_Time, "%d/%m/%Y %H:%M:%S"))
par(mfcol=c(2,2))
with(Power, plot(Date_Time, Global_active_power, xlab= "", ylab= "Global Active Power (kilowattes)",type = "l"))
with(Power, plot(x=c(Date_Time, Date_Time, Date_Time), y = c(Sub_metering_1,Sub_metering_2,Sub_metering_3 ), xlab= "", ylab= "Energy sub metering", type= "n"))
points(Date_Time, Power$Sub_metering_1, type="l")
points(Date_Time, Power$Sub_metering_2, col="red", type="l")
points(Date_Time, Power$Sub_metering_3, col="blue", type="l")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col= c("black", "red", "blue"), lty = 1)
with(Power, plot(Date_Time, Voltage, xlab= "datetime", ylab= "Voltage",type = "l"))
with(Power, plot(Date_Time, Global_reactive_power, xlab= "datetime", ylab= "Global_reactive_power",type = "l"))