library(sqldf)
Power <- read.csv.sql("household_power_consumption.txt","select * from file where Date = '1/2/2007' or Date = '2/2/2007' ",sep=";")
dev.copy(png, file= "plot1.png")
hist(Power$Global_active_power, col="red", main= "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()